# fly.toml app configuration file generated for shallabuf-nats on 2025-05-29T14:43:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shallabuf-nats'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = 'nats-server --port 4222 --http_port 8222'

[http_service]
  internal_port = 8222
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4222
  processes = ['app']

  [[services.ports]]
    port = 4222
    handlers = ['tls']

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
