services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client Port
      - "8222:8222" # Monitoring Port
    command: ["-js", "-m", "8222"]

volumes:
  postgres_data:
  redis_data:
