# fly.toml app configuration file generated for shallabuf-platform on 2025-05-29T14:45:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shallabuf-platform'
primary_region = 'cdg'

[build]

[env]
  NATS_URL = 'nats://sonicus-nats.internal:4222'
  PORT = '8443'
  RUST_ENV = 'prod'
  RUST_LOG = 'info'

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8443
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
