[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
tokio.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["bigdecimal"] }
redis.workspace = true
dotenvy.workspace = true
argon2.workspace = true
config.workspace = true
uuid = { workspace = true, features = ["serde"] }
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
rand.workspace = true
base64.workspace = true
jsonwebtoken.workspace = true
time.workspace = true
hex.workspace = true
base32.workspace = true
sha2.workspace = true
thiserror.workspace = true
reqwest.workspace = true
validator.workspace = true
once_cell.workspace = true
resend-rs.workspace = true
bigdecimal.workspace = true

db.workspace = true
