# fly.toml app configuration file generated for shallabuf-landing on 2025-05-12T22:03:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shallabuf-landing'
primary_region = 'cdg'

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
