name: shallabuf
description: A Pulumi program that deploys a Kubernetes cluster with a PostgreSQL database, NATS messaging server, MinIO object storage, Redis cache, Prometheus monitoring, Loki logging, and Grafana visualization.
runtime:
  name: nodejs
  options:
    packagemanager: auto
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
