/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedOrgsIndexRouteImport } from './routes/_protected/orgs/index'
import { Route as ProtectedOrgsOrgIdAppsRouteImport } from './routes/_protected/orgs/$orgId/apps'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github/callback'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ProtectedOrgsOrgIdMetricsIndexRouteImport } from './routes/_protected/orgs/$orgId/metrics/index'
import { Route as ProtectedOrgsOrgIdSettingsIndexRouteImport } from './routes/_protected/orgs/$orgId/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrgsIndexRoute = ProtectedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgsOrgIdAppsRoute = ProtectedOrgsOrgIdAppsRouteImport.update({
  id: '/orgs/$orgId/apps',
  path: '/orgs/$orgId/apps',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/api/auth/github/callback',
  path: '/api/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrgsOrgIdMetricsIndexRoute =
  ProtectedOrgsOrgIdMetricsIndexRouteImport.update({
    id: '/orgs/$orgId/metrics/',
    path: '/orgs/$orgId/metrics/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrgsOrgIdSettingsIndexRoute =
  ProtectedOrgsOrgIdSettingsIndexRouteImport.update({
    id: '/orgs/$orgId/settings/',
    path: '/orgs/$orgId/settings/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/': typeof LoginIndexRoute
  '/orgs/': typeof ProtectedOrgsIndexRoute
  '/orgs/$orgId/apps': typeof ProtectedOrgsOrgIdAppsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/orgs/$orgId/metrics/': typeof ProtectedOrgsOrgIdMetricsIndexRoute
  '/orgs/$orgId/settings/': typeof ProtectedOrgsOrgIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login': typeof LoginIndexRoute
  '/orgs': typeof ProtectedOrgsIndexRoute
  '/orgs/$orgId/apps': typeof ProtectedOrgsOrgIdAppsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/orgs/$orgId/metrics': typeof ProtectedOrgsOrgIdMetricsIndexRoute
  '/orgs/$orgId/settings': typeof ProtectedOrgsOrgIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/': typeof LoginIndexRoute
  '/_protected/orgs/': typeof ProtectedOrgsIndexRoute
  '/_protected/orgs/$orgId/apps': typeof ProtectedOrgsOrgIdAppsRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/_protected/orgs/$orgId/metrics/': typeof ProtectedOrgsOrgIdMetricsIndexRoute
  '/_protected/orgs/$orgId/settings/': typeof ProtectedOrgsOrgIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/reset-password'
    | '/login/'
    | '/orgs/'
    | '/orgs/$orgId/apps'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/orgs/$orgId/metrics/'
    | '/orgs/$orgId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/reset-password'
    | '/login'
    | '/orgs'
    | '/orgs/$orgId/apps'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/orgs/$orgId/metrics'
    | '/orgs/$orgId/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/accept-invite'
    | '/reset-password'
    | '/login/'
    | '/_protected/orgs/'
    | '/_protected/orgs/$orgId/apps'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/_protected/orgs/$orgId/metrics/'
    | '/_protected/orgs/$orgId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/orgs/': {
      id: '/_protected/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof ProtectedOrgsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgId/apps': {
      id: '/_protected/orgs/$orgId/apps'
      path: '/orgs/$orgId/apps'
      fullPath: '/orgs/$orgId/apps'
      preLoaderRoute: typeof ProtectedOrgsOrgIdAppsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/api/auth/github/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/orgs/$orgId/metrics/': {
      id: '/_protected/orgs/$orgId/metrics/'
      path: '/orgs/$orgId/metrics'
      fullPath: '/orgs/$orgId/metrics/'
      preLoaderRoute: typeof ProtectedOrgsOrgIdMetricsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orgs/$orgId/settings/': {
      id: '/_protected/orgs/$orgId/settings/'
      path: '/orgs/$orgId/settings'
      fullPath: '/orgs/$orgId/settings/'
      preLoaderRoute: typeof ProtectedOrgsOrgIdSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedOrgsIndexRoute: typeof ProtectedOrgsIndexRoute
  ProtectedOrgsOrgIdAppsRoute: typeof ProtectedOrgsOrgIdAppsRoute
  ProtectedOrgsOrgIdMetricsIndexRoute: typeof ProtectedOrgsOrgIdMetricsIndexRoute
  ProtectedOrgsOrgIdSettingsIndexRoute: typeof ProtectedOrgsOrgIdSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOrgsIndexRoute: ProtectedOrgsIndexRoute,
  ProtectedOrgsOrgIdAppsRoute: ProtectedOrgsOrgIdAppsRoute,
  ProtectedOrgsOrgIdMetricsIndexRoute: ProtectedOrgsOrgIdMetricsIndexRoute,
  ProtectedOrgsOrgIdSettingsIndexRoute: ProtectedOrgsOrgIdSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
