/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TextEditorImport } from './routes/text-editor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TextEditorRoute = TextEditorImport.update({
  id: '/text-editor',
  path: '/text-editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/text-editor': {
      id: '/text-editor'
      path: '/text-editor'
      fullPath: '/text-editor'
      preLoaderRoute: typeof TextEditorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/text-editor': typeof TextEditorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/text-editor': typeof TextEditorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/text-editor': typeof TextEditorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/text-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/text-editor'
  id: '__root__' | '/' | '/text-editor'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextEditorRoute: typeof TextEditorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextEditorRoute: TextEditorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/text-editor"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/text-editor": {
      "filePath": "text-editor.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
