name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      platform: ${{ steps.changes.outputs.platform }}
      web: ${{ steps.changes.outputs.web }}
      nats: ${{ steps.changes.outputs.nats }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            platform:
              - 'platform/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
            web:
              - 'web/**'
            nats:
              - 'nats/**'

  deploy-api:
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy API to Fly.io
        run: |
          cd api
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-platform:
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.platform == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Platform to Fly.io
        run: |
          cd platform
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.web == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Web to Fly.io
        run: |
          cd web
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-nats:
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.nats == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy NATS to Fly.io
        run: |
          cd nats
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  # Optional: Deploy all on manual trigger
  deploy-all:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, platform, web, nats]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy ${{ matrix.app }} to Fly.io
        run: |
          if [ "${{ matrix.app }}" = "web" ]; then
            cd web
            flyctl deploy --remote-only
          else
            flyctl deploy --config ./${{ matrix.app }}/fly.toml --remote-only
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
